//
//  main.m
//  cheappod
//
//  Created by iwick on Tue Nov 08 2005.
//  Copyright (c) 2005 __MyCompanyName__. All rights reserved.
//

#import <Cocoa/Cocoa.h>


/*  Xcode 1.5 (and i don't know what gcc, probably 3.3) compile this just fine
		without adding a "const" to the "char *argv[]".
	
    Xcode 1.2 (gcc 3.3) on the university computer gave a warning about argv
		which i fixed by adding const.  This is highly illogical because this
		file main.m is generated by Xcode, not me!
*/

int main(int argc, const char *argv[])
{
    return NSApplicationMain(argc, argv);
}
